### ISSUE TITLE
Error in compiling the module

### ISSUE THREAD

**Issue by Ramys** [azerothcore/mod-npc-free-professions#15]
modules \ mod-npc-free-professions \ src \ ProfessionNPC.cpp (31): warning C4138: '* /' found out of comment.

bool OnGossipSelect(Player *player, Creature */*creature*/, uint32 Sender, uint32 SKILL) override
@Helias

**Comment by Helias** [comment]
Did you update the module at last version? the code seems just wrong, probably you edited it in the wrong way, because your code is
```C++
bool OnGossipSelect(Player *player, Creature */creature/, uint32 Sender, uint32 SKILL) override
```

but actually here in the repository is:
```C++
bool OnGossipSelect(Player *player, Creature */*creature*/, uint32 Sender, uint32 SKILL) override
```

**Comment by Ramys** [comment]
Thank you friend..
I didn't pay attention to that.

**Comment by Helias** [comment]
Don't worry :+1:
