### ISSUE TITLE
Not reusable

### ISSUE THREAD

**Issue by Heijex** [azerothcore/mod-npc-free-professions#2]
Using default core

Once you learn a profession, max it, then unlearn it, you cannot learn that profession from this trainer again.

This trainer appears to only do 2 things. Teaches a profession or max a selective one, nothing more. It looks as if it's suppose to teach recipes as well but I have not encountered this.

**Comment by BarbzYHOOL** [comment]
Module author is not active so someone else should fix it :(

**Comment by talamortis** [comment]
I fixed this last night for @poszer, maybe you should ask him to share?

**Comment by FrancescoBorzi** [comment]
no advertising private work, thanks

**Comment by talamortis** [comment]
How is this advertising private work I was just stating that I managed to fix. Maybe poszer might be kind enough to share.
