### ISSUE TITLE
Bug: Unknown column 'modelid1' in 'field list'

### ISSUE THREAD

**Issue by mehdikhody** [azerothcore/mod-npc-free-professions#29]
### Current Behaviour

ERROR 1054 (42S22) at line 9 in file: 'azerothcore/modules/mod-npc-free-professions/data/sql/db-world/base/mod_npc_free_professions_01.sql': Unknown column 'modelid1' in 'field list'

### Expected Behaviour

It should updated the word database but gives me this error instead.

### Steps to reproduce the problem

`cd modules`
`git clone https://github.com/azerothcore/mod-npc-free-professions.git`
`cd ../`
`./acore.sh 5` - all: clean, configure and compile 
`./acore.sh 11`

### AC rev. hash/commit

None

### Operating system

Ubuntu 20.04

**Comment by Helias** [comment]
the problem is the incompatibility with AC after this PR https://github.com/azerothcore/azerothcore-wotlk/pull/19068
we should make a PR like this one https://github.com/azerothcore/mod-weapon-visual/pull/26 to fix the issue
