### ISSUE TITLE
Not usable - Bugs on AzerothCore 

### ISSUE THREAD

**Issue by Zausender** [azerothcore/mod-npc-free-professions#6]
https://github.com/azerothcore/azerothcore-wotlk/issues/2330

**Comment by BarbzYHOOL** [comment]
Is the module bugged or the command ?

**Comment by Zausender** [comment]
> Is the module bugged or the command ?

Core command which learn/unlearn recipes

**Comment by BarbzYHOOL** [comment]
I don't think modules use the command per say so it's not related to modules

**Comment by Zausender** [comment]
Why closing issue? Did you test what's happening?
https://github.com/azerothcore/mod-npc-free-professions/blob/b315d57cc300b486601bbfa381bfba08851c5357/src/ProfessionNPC.cpp#L119

**Comment by wizzymore** [comment]
This is not related to the command and the error is not related to the module too, it is about the core functionality about professions, we can't do anything until when we don't figure out what is causing this problem

**Comment by Zausender** [comment]
> This is not related to the command and the error is not related to the module too, it is about the core functionality about professions, we can't do anything until when we don't figure out what is causing this problem

More than 2 months without any fix for this and my issue is closed, you should open it and close when its fixed
