### ISSUE TITLE
Unlearn Bug

### ISSUE THREAD

**Issue by V3nomAnc3r** [azerothcore/mod-npc-free-professions#9]
See these links for a better explanation

https://github.com/azerothcore/azerothcore-wotlk/issues/2330
https://github.com/azerothcore/azerothcore-wotlk/issues/478

@wizzymore @IntelligentQuantum

**Comment by IntelligentQuantum** [comment]
@V3nomAnc3r

try this [Professions.cpp](https://gist.github.com/IntelligentQuantum/12712d49ca38a836a30b42ba60c967f0)

**Comment by V3nomAnc3r** [comment]
Wow tnx dude! works perfect

**Comment by Helias** [comment]
We should update the main repo, @IntelligentQuantum could you open a PR?

**Comment by BarbzYHOOL** [comment]
@V3nomAnc3r can you explain why you linked CORE issues in a module??
